version: '3.9'

services:
  api:
    build:
      context: ./api
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app


  client:
    build:
      context: ./client
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
